### ISSUE TITLE
Discuss package contents with upstream author

### ISSUE THREAD

**Issue by ehrenfeu** [imcf/jython-olefile#1]
Hi @decalage2,

I've seen you're watching this repo anyway already, so I thought it's a good opportunity to ask if you're okay with the contents of this package in the current form. Its intention is to make `olefile` available for being used in Fiji / ImageJ (as mentioned in the [README](../blob/master/README.md)).

My question now is whether you are okay with the package contents in their current form, being approximately as follows:
```
jython-olefile-0.46.0.jar
├── CONTRIBUTORS.txt
├── LICENSE.txt
├── META-INF
│   ├── MANIFEST.MF
│   └── maven
│       └── ch.unibas.biozentrum.imcf
│           └── jython-olefile
│               ├── pom.properties
│               └── pom.xml
└── olefile
    ├── __init__.py
    └── olefile.py
```

As you can see it contains mostly the `olefile` directory (unchanged, as being directly taken from your upstream repo), one sub-tree below `META-INF` (auto-generated by Maven during the packaging process) and the files `LICENSE.txt` and `CONTRIBUTORS.txt` (again unchanged from your repo).

Do you have any suggestions, comments, ... about this? Otherwise I would start distributing those `.jar` files through our [ImageJ update site][1].

Thanks for your input!
~Niko

[1]: http://sites.imagej.net/UniBas-IMCF/

**Comment by decalage2** [comment]
Hi @ehrenfeu, it looks good to me, thanks for the heads up!

**Comment by ehrenfeu** [comment]
Great, thanks for the instant feedback @decalage2 !
